## Numpy Arrays

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## 2 dimensional array as two opening brackets [[ and two closing brackets ]]

In [9]:
np.array(my_mat) ## 2 dimensional array as two opening brackets [[ and two closing brackets ]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## np.arange([start],stop,[step]) it work similarly as lists range function.
## Start and Step are optional parameters.

## To get all the elements from 0 to 9 i.e.10 elements.

In [10]:
np.arange(0,10)  ## np.arange(start,stop,step) it work

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## To get all the elements from 0 to 11 i.e 11 elements(from 0 to 10).

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Adding step size of 2 will get the output:

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## Getting number of zeros in an array.

In [13]:
np.zeros(3)

array([0., 0., 0.])

## Getting the number of Zeros by passing the tuple
## np.zeros((5,5)) where first 5 is number of rows and other 5 is number of columns.

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Getting the number of Zeros by passing the tuple
## np.zeros((2,3)) where first 2 is number of rows and other 3 is number of columns.

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## Getting number of ones in an array.

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

## Getting the number of ones by passing the tuple
## np.zeros((3,4)) where first 3 is number of rows and other 4 is number of columns.

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.linspace(start,stop,num=50,endpoint=True,retstep=False, dtype=N one)

## Returns evenly spaced numbers over a specified interval.(by default in 50, if not given anything as parameters.) 

## np.linspace(start=0,stop=5,num=10)

In [18]:
np.linspace(0,5,10) ## 1 dimensional array as one opening [ and one closing] bracket.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## np.linspace(start=0,stop=5,num=100)

In [19]:
np.linspace(0,5,100) ## 1 dimensional array as one opening [ and one closing] bracket.

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

## creating the Identity Matrix.

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Generating random numbers.
##  np.random.(press tab)
## you will able to get various methods from random function.

## np.random.rand(5)
## returns random samples from 0 to 1 which are uniformly distributed.(1 dimensional array.)

In [21]:
np.random.rand(5)

array([0.47975335, 0.51930001, 0.63267104, 0.66391963, 0.05024081])

## In order to generate two dimensional array of matrix 5*5
## np.random.rand(5,5) ## inside tuple.

In [22]:
np.random.rand(5,5)

array([[0.93481977, 0.11001559, 0.77733918, 0.849591  , 0.26129367],
       [0.36763895, 0.42424073, 0.92371313, 0.61040565, 0.64915589],
       [0.76126724, 0.62892921, 0.89412734, 0.89642113, 0.46114375],
       [0.71753975, 0.02837737, 0.66428869, 0.22769499, 0.4216975 ],
       [0.38621823, 0.31677198, 0.25629697, 0.3996029 , 0.35888108]])

## in order to get two random numbers from standard normal distribution or Gaussian distribution.(mu=0,sigma=1).

In [23]:
np.random.randn(2)

array([ 0.32185547, -0.46706055])

## we want two dimensional array
## np.random.randn(4,4) ## inside tuple.

In [24]:
np.random.randn(4,4)

array([[ 0.47838859,  0.79018326,  2.30971186,  1.2899757 ],
       [-1.19238272,  0.73291584, -1.3899086 , -0.04979671],
       [ 1.89681172,  1.61565543,  0.14772608, -1.0146603 ],
       [-2.9435115 , -1.55712211, -0.57758591, -1.38030219]])

## get random numbers from low to high.
## np.random.randint(low,high=None,size=None,dtype='l')
## Return  random integers from low(inclusive) to high(exclusive.)

## random numbers from 1 to 100.

In [25]:
np.random.randint(1,100)

81

## np.random.randint(1,100,10)
## returns random integers from 1 to 100 (total 10 numbers.)

In [26]:
np.random.randint(1,100,10)

array([83, 55, 54,  8, 90, 77, 49, 76, 88, 35])

In [27]:
arr=np.arange(25)

In [28]:
arr ## 1 dimensional array from 0 to 24.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr=np.random.randint(0,50,10)

In [30]:
ranarr

array([40,  1, 46,  5, 24, 17, 45, 39,  5,  2])

## reshape the arr 
## arr.reshape(5,5) where first 5 is the number of rows and second 5 is the number of columns.(2 dimensional array.)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

## you will able to know which combinations of rows and columns  suitable based below data
## array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,17, 18, 19, 20, 21, 22, 23, 24]) i.e.25 elements so 5*5 is suitable combination.(V.V.V.IMP)

## ranarr numbers are always different.

In [33]:
ranarr

array([40,  1, 46,  5, 24, 17, 45, 39,  5,  2])

## ranarr.max()  method returns maximum method of the array.

In [34]:
ranarr.max()

46

## ranarr.min()  method returns maximum method of the array.

In [35]:
ranarr.min()

1

In [36]:
ranarr

array([40,  1, 46,  5, 24, 17, 45, 39,  5,  2])

## ranarr.argmax() method returns index position of the maximum value.

In [37]:
ranarr.argmax()

2

## ranarr.argmin() method returns index position of the minimum value.

In [38]:
ranarr.argmin()

1

## (25,) indicates one dimensional vector.

In [39]:
arr.shape

(25,)

## reshape it to two dimensional vector.

In [40]:
arr=arr.reshape(5,5)

## now checking the shape of the array.

In [41]:
arr.shape ## (5,5) indicates the two dimensional array of 5 rows and 5 columns.

(5, 5)

## to get the datatype of your array.

In [42]:
arr.dtype

dtype('int32')

## if you did not want to import numpy as np then you can write it with following way also.

In [43]:
from numpy.random import randint

In [44]:
randint(2,10)

3

## Numpy indexing and selection.

In [45]:
import numpy as np

In [46]:
arr=np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## get the value of arr[8]

In [48]:
arr[8]

8

## in order to get range of values , we are using slicing which similar to python strings.

In [49]:
arr[1:5]

array([1, 2, 3, 4])

In [50]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [52]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## numpy arrays are different than python lists as numpy arrays are able to broadcast the values.

In [53]:
arr[0:5]=100

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
arr=np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
slice_of_arr=arr[0:6]

In [58]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

## broadcasting on this array.

In [59]:
slice_of_arr[:]=99

In [60]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## This is due to data has not copied but view to the numpy array.

## specifying array's copy method.

In [62]:
arr_copy=arr.copy()

In [63]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## if  i do brodcast on arr_copy so the change will only happens in arr_copy and not in arr.(V.V.V.IMP)

In [65]:
arr_copy[:]=100

In [66]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## indexing 2-d array also known as matrix.

In [68]:
import numpy as np

In [69]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## get the value 5.

In [71]:
arr_2d[0][0]

5

## alternative way.

In [72]:
arr_2d[0,0]

5

## get the entire row.

In [73]:
arr_2d[0]

array([ 5, 10, 15])

## get the value 25.

In [74]:
arr_2d[1][1]

25

## alternative way.

In [75]:
arr_2d[1,1]

25

## get the value 40.

In [76]:
arr_2d[2][1]

40

## alternative way.

In [77]:
arr_2d[2,1]

40

## get the value 30 using alternative way explained above.
## usually used below way as it is less prone to error.

In [78]:
arr_2d[1,2]

30

## get everything upto row 2 and upto column 1.

In [79]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## fetching rows 0 and 1.

In [80]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

## conditional selection.(V.V.V.IMP)

In [81]:
arr=np.arange(1,11)

In [82]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## getting the boolean array.

## returns false where that comparison false and true where that comparison is true.

In [83]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [84]:
arr.dtype

dtype('int32')

In [85]:
bool_arr=arr > 5

In [86]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

## use the bool_arr like arr[bool_arr] and it will return the values where the comparison is true.

In [87]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

## Note:using array with conditional operator returns boolean array and such boolean array has been used for future purpose.

## Alternative way.

In [88]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [89]:
arr[arr<3]

array([1, 2])

In [90]:
arr_2d=np.arange(50).reshape(5,10)

In [91]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

## Grabbing the element 13,14,15,16.

In [92]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [93]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy operations

## Array with Array
## Array with Scalars
## Universal Array Functions

In [94]:
import numpy as np

In [95]:
arr=np.arange(0,11)

In [96]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [98]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [100]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [101]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [102]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [103]:
1/0

ZeroDivisionError: division by zero

In [104]:
arr /arr

C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [105]:
1/arr

C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [106]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

## Universal Array functions

In [107]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [108]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [109]:
np.max(arr)

10

In [110]:
arr.max()

10

In [111]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [112]:
np.log(arr)

C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])